### PR TITLE
Added a way to display metric units

### PR DESCRIPTION
**Pull request by AntoineTA**
+ added a global setting to render strings with imperial units as metric units (e.g. 30 ft. > 9 m), as per https://github.com/5etools/tracker/issues/29
+ corrected a bug where speed unit would not appear for mounts
- removed metric handler in parser.js as it is now redundant

### CODE REVIEW

**Comment by revilowaldow** [comment]
Does this handle temperatures on `recipes.html`? As that would be a great addition as per https://github.com/5etools/tracker/issues/1097
They're easily identifiable from the `°F` unit following them.

**Comment by AntoineTA** [comment]
It does not currently support conversion to Celsius, but I can look into
it. It should not be too complicated...

Le dim. 31 juil. 2022 à 16:29, revilowaldow ***@***.***> a
écrit :

**Comment by TheGiddyLimit** [comment]
I'll have a proper look/think about this when I get time, but at a skim/gut reaction:

- The existing metric methods were (only?) used in Plutonium, where somewhat-granular metric conversion is done. Having a single global switch is therefore not good enough
- This is a dirty hack; "just regex it" really isn't good enough. You've also removed bits where I had specifically avoided doing this, e.g. in race speed rendering, which has me a little confused--there was clearly effort _not_ to do the "bad" thing. Why are we regressing here?

**Comment by AntoineTA** [comment]
Thank you for you message! You are right, this is most definitely a dirty
hack. Unfortunaly, I am unsure how to do it better, especially for those
unit strings that are not clearly identified in the data (such as those in
a spell description)...

Anyway, feel free to close the PR if you think it is not worth the trouble.

**Pull request closed without merging**
