### PR TITLE
Art credit 3: The Rebase of the Sith

### PR DESCRIPTION
**Pull request by revilowaldow**
Here we go, hopefully lighter touch this time.
... I'm sure immediately reworking the back of RMR isn't a omen of how this will go.

### CODE REVIEW

**Comment by revilowaldow** [comment]
I was making more typos than I was comfortable with while hand implementing this.
Many common names are already caught by the spellchecker, and many artists appear multiple times.
I'm confident adding this new list has merit.

**Comment by revilowaldow** [comment]
@TheGiddyLimit This one's ready for review now. 
This is all the books with art credit, and any adventures that come with those books. 
There's some adventures left to do but would rather do a second PR for those as don't have much free time at the moment and want to get this in before it starts to diverge from master much more.
If you're alright with me leaving it with 'conflicts' that would be great as I really struggle with rebasing for some reason, I think I'm just fundamentally misunderstanding how I'm supposed to do something or missing a step etc.

**Comment by TheGiddyLimit** [comment]
fookin clean; merged to main for next release

fwiw the It Just Works trick to rebasing, is to avoid the problem by only ever having one commit on your branch. So, either do everything as one massive commit in one branch (which I'm totally happy with for this sort of data scrubbing), or have many branches with e.g. one commit for each file/piece of work done. It then becomes ~trivial to rebase

One's local workflow then becomes `work` -> `amend commit` rather than `work` -> `commit`, and force-pushing the ever-growing commit every time

**Comment by revilowaldow** [comment]
Thank you for the tip, greatly appreciated, I'll try to minimise commit count in future 👍

**Pull request closed without merging**
