### PR TITLE
Updates to variantrules.json

### PR DESCRIPTION
**Pull request by Zkaij**
- Added Wild Shape Forms optional rule from UADruid
- Added ruleType VO (Variant Optional) to Greyhawk Initiative
- Converted em- to en-dashes where appropriate and literals (vast minority) to Unicode escapes for consistency
- Added various page/table/spell/etc. links (being conservative)
- First time doing something like this, hope I did well

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
Looks good!

What does:

> and literals (vast minority) to Unicode escapes for consistency

refer to?

**Comment by Zkaij** [comment]
Glad to hear (^: That line is referring to em-dashes being written as both '—' and '\u2014' in different places: I noticed that some were written as Unicode escapes (\uXXXX), so I scanned to see whether there were any literals (—) in case there was a preference for one over the other—not that there seems to be any issue with the handling or rendering on the site. Since there were only three(!) literals (and about 158 escapes), I replaced them with the escape sequence, and inserted the four instances in the new entry as escapes too, so that they're all the same now. The en-dashes were also inserted as escapes too.
Also, I forgot to note that I didn't replace ems with ens in the case of references (e.g. the DMG treasure hoard tables, which mistakenly use em-dashes for the CR ranges in their names).

**Comment by revilowaldow** [comment]
FYI: From README.md

#### Character replacement

- `’` should be replaced with `'`
- `“` and `”` should be replaced with `"`
- `—` (em dash) should be replaced with `\u2014` (Unicode for em dash)
- `–` should be replaced with `\u2013` (Unicode for en dash)
- `−` should be replaced with `\u2212` (Unicode for minus sign)
- `•` should be not be used unless the JSON in question is not yet covered by the entryRenderer, i.e. should be encoded as a list
- the only Unicode escape sequences allowed are `\u2014`, `\u2013`, and `\u2212`; all other characters (unless noted above) should be stored as-is

#### Convention for dashes

- `-` (hyphen) should **only** be used to hyphenate words, e.g. `60-foot` and `18th-level`
- `\u2014` should be used for parenthetical dash pairs, or for marking empty table rows.
- `\u2013` should be used for joining numerical ranges, e.g. `1-5` should become `1\u20135`.
- `\u2212` should be used for unary minus signs, in the case of penalties. For example, `"You have a -5 penalty to..."` should become `"You have a \u22125 penalty to..."`.
- any whitespace on any side of a `\u2014` should be removed

**Comment by Zkaij** [comment]
Apologies for the spaces around the em-dashes. That's my mistake: I was trying to replicate the source faithfully, but I should have checked. Thanks for mentioning (^:

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by TheGiddyLimit** [comment]
Merged for next release

**Comment by Zkaij** [comment]
Glad to hear (^: That line is referring to whether the text is '—' or '\u2014'. I noticed that some em-dashes were written as Unicode escapes (\uXXXX), so I scanned to see whether there were any literals (—) in case there was a preference for one over the other—not that there seems to be any issue with the handling or rendering on the site. Since there were only three literals (and about 158 escapes), I replaced them with the escape sequence, and inserted the four instances in the new entry as escapes too.
________________________________

**Pull request closed without merging**
