### PR TITLE
Add 5eTools `{@tag }` Syntax Highlighting to Ace

### PR DESCRIPTION
**Pull request by revilowaldow**
- Recognizes valid tag keywords
- Recognizes valid sources, including both core and homebrew
- Tags not highlighting provides user feedback that their tag is in some way incorrect

image

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
very cool, and it has some effect for me, but seems to throw a ton of errors 🤔:

image

I'm also not quite seeing the same highlighting you've pictured:

image

What am I doing wrong?

**Comment by revilowaldow** [comment]
I copy-pasted this into GitHub’s web edit box. So likely an error on transferring it on my part, will review this evening.

**Comment by revilowaldow** [comment]
Just a hunch; do you have any homebrew added? Maybe if the list of sources is empty then the regex is trying to match `||` after the string is joined? Ensuring the BrewSources var always has something in it by tacking `+ "|Brew"` on the end may make it work? Haven't tested this

**Comment by TheGiddyLimit** [comment]
That would make sense, and no, I don't think I had any homebrew loaded

**Comment by revilowaldow** [comment]
It's definitely the brew sources thing, will have a new commit soon, just trying to make the source matching completely case insensitive.

**Comment by TheGiddyLimit** [comment]
Can you just call `toString` on one you made from a string? i.e., `new RegExp("\\btest\\b").toString()`. I believe that includes the flags (and some slashes), however

**Comment by revilowaldow** [comment]
> Can you just call `toString` on one you made from a string? i.e., `new RegExp("\\btest\\b").toString()`. I believe that includes the flags (and some slashes), however

Unfortunately it doesn't seem to work. Looking at the generated string it seems to be a valid expression, but I think whatever ace is doing in the background doesn't seem to accept a string containing delimited regexp. Though just delimited regex by itself doesn't seem to work either which is odd, even if entered manually or as a variable. 

Have also made an improvement to only start the tag highlighting if the following keyword is valid.

**Comment by revilowaldow** [comment]
What a mess, didn't realise that renaming the branch would nuke the pull request.

**Review by TheGiddyLimit — APPROVED** [review]
Works on my machine

**Comment by TheGiddyLimit** [comment]
Merged to main for next release

**Pull request closed without merging**
