### PR TITLE
Replace the terms "blacklist" and "whitelist"

### PR DESCRIPTION
**Pull request by mtilda**
## Purpose

The terms "blacklist" and "whitelist" are controversial due to their etymological relation to slavery, segregation, racism. I am not a subject matter expert on race, linguistics, or history; however I support the opinion that we should replace these terms with modern denotational synonyms.

I did this in my own fork and thought others may like the same.

### Find and replace

First, perform a set of simple find-and-replace operations on file names and their content (as shown below).
`blacklist` → `blocklist`
`Blacklist` → `Blocklist`
`BLACKLIST` → `BLOCKLIST`
`whitelist` → `allowlist`
`Whitelist` → `Allowlist`
`WHITELIST` → `ALLOWLIST`

### Backward compatibility for "content-blacklist" JSON files

Next, manually make some corrections to `js/blocklist-ui.js` to maintain backwards compatibility of the "Import List" button with old "content-blacklist" JSON files.

#### Old export example
```json
{
	"siteVersion": "1.167.9",
	"fileType": "content-blacklist",
	"blacklist": []
}
```

#### New export example
```json
{
	"siteVersion": "1.167.9",
	"fileType": "content-blocklist",
	"disallowlist": []
}
```

## Test

I have manually tested that I am able to
- Export and import the new "content-blocklist" file, and still
- Import the old "content-blacklist" file.

---

Screen Shot 2022-09-28 at 12 11 15

---

EDIT: Renamed "disallowlist" to "blocklist" everywhere

### CODE REVIEW

**Comment by revilowaldow** [comment]
Having previously suggested this in the community discord, and bearing in mind your response at the time Giddy, I'd like to reaffirm my support for this change.

The work appears to already be done (though Plutonium, the homebrew repo and maybe the utils module would need more to match), and this change disadvantages nobody with its inclusion.

Even if someone is apathetic to the change, they could see how if it's already done, just merging it shouldn't be an issue.

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
`disallowlist` -> `blocklist`, please, the former is a bit too cumbersome for my tastes

**Comment by mtilda** [comment]
> `disallowlist` -> `blocklist`, please, the former is a bit too cumbersome for my tastes

Sounds good 😊 Made the change!

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by TheGiddyLimit** [comment]
Merged to main repo for next release

**Pull request closed without merging**
