### PR TITLE
Implement Artist Credit 2: Rebase boogaloo

### PR DESCRIPTION
**Pull request by revilowaldow**
This PR aims to tag artist image credits in line with how artist credit is given in print copies of official 5e materials.
That is; after approximately mid-2019, starting with LLK for adventures and RMR for books, small footnotes appear against almost all art including maps.
Some exceptions exist such as the Plane Shift series which included artist credit prior to the mid-2019 introduction of specific crediting.
Where a piece of art is reprinted from a pre-2019 source in a later source, the credit will be back-ported to all instances of the image, this is expected to affect e.g. MM fluff images

The fluff for Plane Shift Zendikar and Plane Shift Innistrad has been completely overhauled and similar improvements are expected for other Planeshift sources.

Turns out I'm so bad at rebasing/merging that creating a new branch and just doing a big temporary copy is easier.

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
@revilowaldow before I forget, what was that tagging script we were to make a note of running?

Also, if there's any bits of this it would make sense to break out into individual PRs (e.g. PS fluff), then do let me know; happy to merge finished chunks as you go, equally happy to do one giant merge at the end

**Comment by revilowaldow** [comment]
> @revilowaldow before I forget, what was that tagging script we were to make a note of running?
> 

Bestiary tagging of the new forced save things 

> Also, if there's any bits of this it would make sense to break out into individual PRs (e.g. PS fluff), then do let me know; happy to merge finished chunks as you go, equally happy to do one giant merge at the end

Yeah was def intending to do "all the ps fluff" as one pr and then move onto lighter touch stuff in a follow up pr, in contrast to original intent 👌

**Comment by revilowaldow** [comment]
Relatively significant changes to the Knowledge Domain subclass in PSA.
It turns it from being near useless to something you'd actually choose to import to a character. I'm comfortable that it's still sufficiently distinct on the classes page with sources clear. Let me know if you want changes.

Note how it has content, sources are still identified.
### Old:
image
### New:
image

**Comment by revilowaldow** [comment]
Ahh fuck it. All yours Giddy.

**Comment by TheGiddyLimit** [comment]
excellent work; merged to main for next release

**Pull request closed without merging**
